using System.Collections.Immutable;
using System.Diagnostics;
using System.Linq;
using System.Text;
using MediaThor.SourceGenerator.Infrastructure;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;

namespace MediaThor.SourceGenerator.RequestHandler;

public sealed partial class RequestHandlerSourceGenerator
{
    private static void GenerateMediaThorDispatcher(SourceProductionContext context,
        ImmutableArray<RequestHandlerInformation> requestHandlersInformation)
    {
        var writer = new SourceCodeWriter()
            .AppendLine("// <auto-generated>")
            .AppendLine("//     This code was generated by MediaThor.SourceGenerator.RequestHandlerSourceGenerator.")
            .AppendLine(
                "//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.")
            .AppendLine("// </auto-generated>")
            .AppendLine()
            .AppendLine("using MediaThor;")
            .AppendLine("using Microsoft.Extensions.DependencyInjection;")
            .AppendLine()
            .AppendLine("public sealed class MediaThorDispatcher")
            .AppendIndentedLine(": IMediaThorDispatcher");

        using (writer.CreateScope())
        {
            writer.AppendLine(
                    "private RequestHandlerDelegate<TResponse> BuildPipeline<TRequest, TResponse>(TRequest request, IServiceProvider serviceProvider)")
                .AppendIndentedLine("where TRequest : IRequest<TResponse>");
            using (writer.CreateScope())
            {
                writer
                    .AppendLine("RequestHandlerDelegate<TResponse> pipeline = token => serviceProvider.GetRequiredService<MediaThor.IRequestHandler<TRequest, TResponse>>().HandleAsync(request, token);")
                    .AppendLine()
                    .AppendLine("foreach (var behavior in serviceProvider.GetServices<IPipelineBehavior<TRequest, TResponse>>().Reverse())");
                using (writer.CreateScope())
                {
                    writer
                        .AppendLine("var next = pipeline;")
                        .AppendLine("pipeline = (ct) => behavior.HandleAsync(request, next, ct);");
                }

                writer
                    .AppendLine()
                    .AppendLine("return pipeline;");
            }
            
            writer.AppendLine()
                .AppendLine(
                "public Task<TResponse> Dispatch<TResponse>(IServiceProvider serviceProvider, IRequest<TResponse> request, CancellationToken cancellationToken)");
            using (writer.CreateScope())
            {
                writer.AppendLine("return request switch")
                    .AppendLine("{");

                writer.IndentationLevel++;

                foreach (var handledType in requestHandlersInformation.SelectMany(r => r.HandledTypes))
                {
                    var splitHandledType = handledType.Split('<', ',', '>');
                    
                    writer
                        .AppendIndent()
                        .Append(splitHandledType[1])
                        .Append(" q => (Task<TResponse>)(object)(BuildPipeline<")
                        .Append(splitHandledType[1])
                        .Append(", ")
                        .Append(splitHandledType[2].TrimStart())
                        .Append(">(q, serviceProvider).Invoke(cancellationToken)),")
                        .AppendLine();
                }

                writer.AppendLine("_ => throw new InvalidOperationException($\"No handler registered for request {request.GetType()}.\")");

                writer.IndentationLevel--;
                
                writer.AppendLine("};");
            }
        }
        
        context.AddSource("MediaThorDispatcher.g.cs", SourceText.From(writer.ToString(), Encoding.UTF8));
    }

    private static void GenerateMediaThorServiceCollectionExtensions(SourceProductionContext context,
        ImmutableArray<PipelineBehaviorInformation> pipelineBehaviorInformation, ImmutableArray<RequestHandlerInformation> requestHandlersInformation)
    {
        var writer = new SourceCodeWriter()
            .AppendLine("// <auto-generated>")
            .AppendLine("//     This code was generated by MediaThor.SourceGenerator.RequestHandlerSourceGenerator.")
            .AppendLine(
                "//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.")
            .AppendLine("// </auto-generated>")
            .AppendLine()
            .AppendLine("using Microsoft.Extensions.DependencyInjection;")
            .AppendLine()
            .AppendLine("public static class MediaThorServiceCollectionExtensions");

        using (writer.CreateScope())
        {
            writer.AppendLine(
                "public static IServiceCollection AddMediaThor(this IServiceCollection services)");

            using (writer.CreateScope())
            {
                writer.AppendLine("services.AddTransient<MediaThor.IMediaThor, MediaThor.MediaThor>();")
                    .AppendLine("services.AddSingleton<MediaThor.IMediaThorDispatcher, MediaThorDispatcher>();");
                
                if (requestHandlersInformation.Length > 0)
                    writer.AppendLine();
                
                foreach (var requestHandlerInformation in requestHandlersInformation)
                {
                    foreach (var handledType in requestHandlerInformation.HandledTypes)
                    {
                        writer
                            .AppendIndent()
                            .Append("services.AddScoped<")
                            .Append(handledType)
                            .Append(", ")
                            .Append(requestHandlerInformation.HandlerTypeName)
                            .Append(">();")
                            .AppendLine();
                    }
                }
                
                if (pipelineBehaviorInformation.Length > 0)
                    writer.AppendLine();
                
                foreach (var pipeline in pipelineBehaviorInformation.OrderBy(p => p.Priority))
                {
                    foreach (var pipelineHandling in pipeline.InterfacePipelineName)
                    {
                        writer
                            .AppendIndent()
                            .Append("services.AddScoped(typeof(")
                            .Append(pipelineHandling)
                            .Append("), typeof(")
                            .Append(pipeline.PipelineName)
                            .Append("));")
                            .AppendLine();
                    }
                }
                
                writer
                    .AppendLine()
                    .AppendLine("return services;");
            }
        }
        
        context.AddSource("MediaThorServiceCollectionExtensions.g.cs", SourceText.From(writer.ToString(), Encoding.UTF8));
    }
}