using System.Collections.Immutable;
using System.Diagnostics;
using System.Linq;
using System.Text;
using MediaThor.SourceGenerator.Infrastructure;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;

namespace MediaThor.SourceGenerator.RequestHandler;

public sealed partial class RequestHandlerSourceGenerator
{
    private static void GenerateMediaThorHandlerProvider(SourceProductionContext context, ImmutableArray<RequestHandlerInformation> requestHandlerInformations,
        ImmutableArray<RequestHandlerInformation> genericRequestHandlersInformation, ImmutableArray<RequestHandlerInformation> streamRequestHandlersInformation)
    {
        var writer = new SourceCodeWriter()
            .AppendLine("// <auto-generated>")
            .AppendLine("//     This code was generated by MediaThor.SourceGenerator.RequestHandlerSourceGenerator.")
            .AppendLine(
                "//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.")
            .AppendLine("// </auto-generated>")
            .AppendLine()
            .AppendLine("using System;")
            .AppendLine("using System.Collections.Generic;")
            .AppendLine("using System.Threading;")
            .AppendLine("using MediaThor;")
            .AppendLine("using Microsoft.Extensions.DependencyInjection;")
            .AppendLine()
            .AppendLine("public sealed class MediaThorHandlerProvider")
            .AppendIndentedLine(": IMediaThorHandlerProvider");
        using (writer.CreateScope())
        {
            writer
                .AppendLine("private readonly Dictionary<Type, Func<IServiceProvider, object, object>> _responseHandlers;")
                .AppendLine();

            writer.AppendLine("public MediaThorHandlerProvider(IPipelineBuilder pipelineBuilder)");
            using (writer.CreateScope())
            {
                writer.AppendLine("_responseHandlers = new Dictionary<Type, Func<IServiceProvider, object, object>>()")
                    .AppendLine('{');
                writer.IndentationLevel++;

                foreach (var handledType in requestHandlerInformations
                             .SelectMany(static x => x.HandledTypes))
                {
                    var requestType = handledType.Split('<', ',', '>')[1];

                    writer
                        .AppendIndent()
                        .Append("[typeof(")
                        .Append(requestType)
                        .Append(")] = (serviceProvider, request) =>")
                        .AppendLine();
                    
                    writer.IndentationLevel++;
                    writer
                        .AppendIndent()
                        .Append("pipelineBuilder.BuildPipeline((")
                        .Append(requestType)
                        .Append(")request, serviceProvider, (RequestHandlerDelegate)(token => serviceProvider.GetRequiredService<")
                        .Append(handledType)
                        .Append(">().HandleAsync((")
                        .Append(requestType)
                        .Append(")request, token))),")
                        .AppendLine();
                    writer.IndentationLevel--;
                }
                
                foreach (var handledType in genericRequestHandlersInformation
                             .SelectMany(static x => x.HandledTypes))
                {
                    var splitTypeInfo = handledType.Split('<', ',', '>');
                    var requestType = splitTypeInfo[1];
                    var responseType =  splitTypeInfo[2].TrimStart();

                    writer
                        .AppendIndent()
                        .Append("[typeof(")
                        .Append(requestType)
                        .Append(")] = (serviceProvider, request) =>")
                        .AppendLine();
                    
                    writer.IndentationLevel++;
                    writer
                        .AppendIndent()
                        .Append("pipelineBuilder.BuildPipeline((")
                        .Append(requestType)
                        .Append(")request, serviceProvider, (RequestHandlerDelegate<")
                        .Append(responseType)
                        .Append(">)(token => serviceProvider.GetRequiredService<")
                        .Append(handledType)
                        .Append(">().HandleAsync((")
                        .Append(requestType)
                        .Append(")request, token))),")
                        .AppendLine();
                    writer.IndentationLevel--;
                }
                
                foreach (var handledType in streamRequestHandlersInformation
                             .SelectMany(static x => x.HandledTypes))
                {
                    var splitTypeInfo = handledType.Split('<', ',', '>');
                    var requestType = splitTypeInfo[1];
                    var responseType =  splitTypeInfo[2].TrimStart();

                    writer
                        .AppendIndent()
                        .Append("[typeof(")
                        .Append(requestType)
                        .Append(")] = (serviceProvider, request) =>")
                        .AppendLine();
                    
                    writer.IndentationLevel++;
                    writer
                        .AppendIndent()
                        .Append("(RequestHandlerDelegate<IAsyncEnumerable<")
                        .Append(responseType)
                        .Append(">>)(token => Task.FromResult(serviceProvider.GetRequiredService<")
                        .Append(handledType)
                        .Append(">().HandleAsync((")
                        .Append(requestType)
                        .Append(")request, token))),")
                        .AppendLine();
                    writer.IndentationLevel--;
                }
                
                writer.IndentationLevel--;
                writer.AppendLine("};");
            }

            writer.AppendLine()
                .AppendLine("/// <inheritdoc/>")
                .AppendLine("public RequestHandlerDelegate TryGetHandler(IServiceProvider serviceProvider, IRequest request)");
            using (writer.CreateScope())
            {
                writer.AppendLine("return _responseHandlers.TryGetValue(request.GetType(), out var handler) ? (RequestHandlerDelegate)handler(serviceProvider, request) : null;");
            }

            writer.AppendLine()
                .AppendLine("/// <inheritdoc/>")
                .AppendLine("public RequestHandlerDelegate<TResponse> TryGetHandler<TResponse>(IServiceProvider serviceProvider, IRequest<TResponse> request)");
            using (writer.CreateScope())
            {
                writer.AppendLine("return _responseHandlers.TryGetValue(request.GetType(), out var handler) ? (RequestHandlerDelegate<TResponse>)handler(serviceProvider, request) : null;");
            }
        }
        
        context.AddSource("MediaThorHandlerProvider.g.cs", SourceText.From(writer.ToString(), Encoding.UTF8));
    }
    
    private static void GenerateMediaThorServiceCollectionExtensions(SourceProductionContext context,
        ImmutableArray<PipelineBehaviorInformation> pipelineBehaviorInformation,
        ImmutableArray<RequestHandlerInformation> genericRequestHandlersInformation,
        ImmutableArray<RequestHandlerInformation> streamRequestHandlersInformation,
        ImmutableArray<RequestHandlerInformation> requestHandlersInformation)
    {
        var writer = new SourceCodeWriter()
            .AppendLine("// <auto-generated>")
            .AppendLine("//     This code was generated by MediaThor.SourceGenerator.RequestHandlerSourceGenerator.")
            .AppendLine(
                "//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.")
            .AppendLine("// </auto-generated>")
            .AppendLine()
            .AppendLine("using MediaThor.Extensions;")
            .AppendLine("using Microsoft.Extensions.DependencyInjection;")
            .AppendLine()
            .AppendLine("public static class MediaThorServiceCollectionExtensions");

        using (writer.CreateScope())
        {
            writer.AppendLine(
                "public static IServiceCollection AddMediaThor(this IServiceCollection services)");

            using (writer.CreateScope())
            {
                writer
                    .AppendLine("services.AddMediathorServices()")
                    .AppendIndentedLine(".AddSingleton<MediaThor.IMediaThorHandlerProvider, MediaThorHandlerProvider>();");

                if (requestHandlersInformation.Length > 0
                    || genericRequestHandlersInformation.Length > 0
                    || streamRequestHandlersInformation.Length > 0)
                    writer.AppendLine();
                
                foreach (var requestHandlerInformation in requestHandlersInformation
                             .Concat(genericRequestHandlersInformation)
                             .Concat(streamRequestHandlersInformation))
                {
                    foreach (var handledType in requestHandlerInformation.HandledTypes)
                    {
                        writer
                            .AppendIndent()
                            .Append("services.AddScoped<")
                            .Append(handledType)
                            .Append(", ")
                            .Append(requestHandlerInformation.HandlerTypeName)
                            .Append(">();")
                            .AppendLine();
                    }
                }
                
                if (pipelineBehaviorInformation.Length > 0)
                    writer.AppendLine();
                
                foreach (var pipeline in pipelineBehaviorInformation.OrderBy(p => p.Priority))
                {
                    foreach (var pipelineHandling in pipeline.InterfacePipelineName)
                    {
                        writer
                            .AppendIndent()
                            .Append("services.AddScoped(typeof(")
                            .Append(pipelineHandling)
                            .Append("), typeof(")
                            .Append(pipeline.PipelineName)
                            .Append("));")
                            .AppendLine();
                    }
                }
                
                writer
                    .AppendLine()
                    .AppendLine("return services;");
            }
        }
        
        context.AddSource("MediaThorServiceCollectionExtensions.g.cs", SourceText.From(writer.ToString(), Encoding.UTF8));
    }
}